export const countries: any = {
  AF: 'Afghanistan',
  AL: 'Albania',
  DZ: 'Algeria',
  AS: 'American Samoa',
  AD: 'Andorra',
  AO: 'Angola',
  AI: 'Anguilla',
  AQ: 'Antarctica',
  AG: 'Antigua and Barbuda',
  AR: 'Argentina',
  AM: 'Armenia',
  AW: 'Aruba',
  AU: 'Australia',
  AT: 'Austria',
  AZ: 'Azerbaijan',
  BS: 'Bahamas (the)',
  BH: 'Bahrain',
  BD: 'Bangladesh',
  BB: 'Barbados',
  BY: 'Belarus',
  BE: 'Belgium',
  BZ: 'Belize',
  BJ: 'Benin',
  BM: 'Bermuda',
  BT: 'Bhutan',
  BO: 'Bolivia (Plurinational State of)',
  BQ: 'Bonaire, Sint Eustatius and Saba',
  BA: 'Bosnia and Herzegovina',
  BW: 'Botswana',
  BV: 'Bouvet Island',
  BR: 'Brazil',
  IO: 'British Indian Ocean Territory (the)',
  BN: 'Brunei Darussalam',
  BG: 'Bulgaria',
  BF: 'Burkina Faso',
  BI: 'Burundi',
  CV: 'Cabo Verde',
  KH: 'Cambodia',
  CM: 'Cameroon',
  CA: 'Canada',
  KY: 'Cayman Islands (the)',
  CF: 'Central African Republic (the)',
  TD: 'Chad',
  CL: 'Chile',
  CN: 'China',
  CX: 'Christmas Island',
  CC: 'Cocos (Keeling) Islands (the)',
  CO: 'Colombia',
  KM: 'Comoros (the)',
  CD: 'Congo (the Democratic Republic of the)',
  CG: 'Congo (the)',
  CK: 'Cook Islands (the)',
  CR: 'Costa Rica',
  HR: 'Croatia',
  CU: 'Cuba',
  CW: 'Curaçao',
  CY: 'Cyprus',
  CZ: 'Czechia',
  CI: "Côte d'Ivoire",
  DK: 'Denmark',
  DJ: 'Djibouti',
  DM: 'Dominica',
  DO: 'Dominican Republic (the)',
  EC: 'Ecuador',
  EG: 'Egypt',
  SV: 'El Salvador',
  GQ: 'Equatorial Guinea',
  ER: 'Eritrea',
  EE: 'Estonia',
  SZ: 'Eswatini',
  ET: 'Ethiopia',
  FK: 'Falkland Islands (the) [Malvinas]',
  FO: 'Faroe Islands (the)',
  FJ: 'Fiji',
  FI: 'Finland',
  FR: 'France',
  GF: 'French Guiana',
  PF: 'French Polynesia',
  TF: 'French Southern Territories (the)',
  GA: 'Gabon',
  GM: 'Gambia (the)',
  GE: 'Georgia',
  DE: 'Germany',
  GH: 'Ghana',
  GI: 'Gibraltar',
  GR: 'Greece',
  GL: 'Greenland',
  GD: 'Grenada',
  GP: 'Guadeloupe',
  GU: 'Guam',
  GT: 'Guatemala',
  GG: 'Guernsey',
  GN: 'Guinea',
  GW: 'Guinea-Bissau',
  GY: 'Guyana',
  HT: 'Haiti',
  HM: 'Heard Island and McDonald Islands',
  VA: 'Holy See (the)',
  HN: 'Honduras',
  HK: 'Hong Kong',
  HU: 'Hungary',
  IS: 'Iceland',
  IN: 'India',
  ID: 'Indonesia',
  IR: 'Iran (Islamic Republic of)',
  IQ: 'Iraq',
  IE: 'Ireland',
  IM: 'Isle of Man',
  IL: 'Israel',
  IT: 'Italy',
  JM: 'Jamaica',
  JP: 'Japan',
  JE: 'Jersey',
  JO: 'Jordan',
  KZ: 'Kazakhstan',
  KE: 'Kenya',
  KI: 'Kiribati',
  KP: "Korea (the Democratic People's Republic of)",
  KR: 'Korea (the Republic of)',
  KW: 'Kuwait',
  KG: 'Kyrgyzstan',
  LA: "Lao People's Democratic Republic (the)",
  LV: 'Latvia',
  LB: 'Lebanon',
  LS: 'Lesotho',
  LR: 'Liberia',
  LY: 'Libya',
  LI: 'Liechtenstein',
  LT: 'Lithuania',
  LU: 'Luxembourg',
  MO: 'Macao',
  MG: 'Madagascar',
  MW: 'Malawi',
  MY: 'Malaysia',
  MV: 'Maldives',
  ML: 'Mali',
  MT: 'Malta',
  MH: 'Marshall Islands (the)',
  MQ: 'Martinique',
  MR: 'Mauritania',
  MU: 'Mauritius',
  YT: 'Mayotte',
  MX: 'Mexico',
  FM: 'Micronesia (Federated States of)',
  MD: 'Moldova (the Republic of)',
  MC: 'Monaco',
  MN: 'Mongolia',
  ME: 'Montenegro',
  MS: 'Montserrat',
  MA: 'Morocco',
  MZ: 'Mozambique',
  MM: 'Myanmar',
  NA: 'Namibia',
  NR: 'Nauru',
  NP: 'Nepal',
  NL: 'Netherlands (the)',
  NC: 'New Caledonia',
  NZ: 'New Zealand',
  NI: 'Nicaragua',
  NE: 'Niger (the)',
  NG: 'Nigeria',
  NU: 'Niue',
  NF: 'Norfolk Island',
  MP: 'Northern Mariana Islands (the)',
  NO: 'Norway',
  OM: 'Oman',
  PK: 'Pakistan',
  PW: 'Palau',
  PS: 'Palestine, State of',
  PA: 'Panama',
  PG: 'Papua New Guinea',
  PY: 'Paraguay',
  PE: 'Peru',
  PH: 'Philippines (the)',
  PN: 'Pitcairn',
  PL: 'Poland',
  PT: 'Portugal',
  PR: 'Puerto Rico',
  QA: 'Qatar',
  MK: 'Republic of North Macedonia',
  RO: 'Romania',
  RU: 'Russian Federation (the)',
  RW: 'Rwanda',
  RE: 'Réunion',
  BL: 'Saint Barthélemy',
  SH: 'Saint Helena, Ascension and Tristan da Cunha',
  KN: 'Saint Kitts and Nevis',
  LC: 'Saint Lucia',
  MF: 'Saint Martin (French part)',
  PM: 'Saint Pierre and Miquelon',
  VC: 'Saint Vincent and the Grenadines',
  WS: 'Samoa',
  SM: 'San Marino',
  ST: 'Sao Tome and Principe',
  SA: 'Saudi Arabia',
  SN: 'Senegal',
  RS: 'Serbia',
  SC: 'Seychelles',
  SL: 'Sierra Leone',
  SG: 'Singapore',
  SX: 'Sint Maarten (Dutch part)',
  SK: 'Slovakia',
  SI: 'Slovenia',
  SB: 'Solomon Islands',
  SO: 'Somalia',
  ZA: 'South Africa',
  GS: 'South Georgia and the South Sandwich Islands',
  SS: 'South Sudan',
  ES: 'Spain',
  LK: 'Sri Lanka',
  SD: 'Sudan (the)',
  SR: 'Suriname',
  SJ: 'Svalbard and Jan Mayen',
  SE: 'Sweden',
  CH: 'Switzerland',
  SY: 'Syrian Arab Republic',
  TW: 'Taiwan (Province of China)',
  TJ: 'Tajikistan',
  TZ: 'Tanzania, United Republic of',
  TH: 'Thailand',
  TL: 'Timor-Leste',
  TG: 'Togo',
  TK: 'Tokelau',
  TO: 'Tonga',
  TT: 'Trinidad and Tobago',
  TN: 'Tunisia',
  TR: 'Turkey',
  TM: 'Turkmenistan',
  TC: 'Turks and Caicos Islands (the)',
  TV: 'Tuvalu',
  UG: 'Uganda',
  UA: 'Ukraine',
  AE: 'United Arab Emirates (the)',
  GB: 'United Kingdom of Great Britain and Northern Ireland (the)',
  UM: 'United States Minor Outlying Islands (the)',
  US: 'United States of America (the)',
  UY: 'Uruguay',
  UZ: 'Uzbekistan',
  VU: 'Vanuatu',
  VE: 'Venezuela (Bolivarian Republic of)',
  VN: 'Viet Nam',
  VG: 'Virgin Islands (British)',
  VI: 'Virgin Islands (U.S.)',
  WF: 'Wallis and Futuna',
  EH: 'Western Sahara',
  YE: 'Yemen',
  ZM: 'Zambia',
  ZW: 'Zimbabwe',
  AX: 'Åland Islands',
  XK: 'Kosovo',
  AC: 'Ascension',
  TA: 'Tristan da Cunha',
};

export const countriesAr: any = {
  AF: 'أفغانستان',
  AL: 'ألبانيا',
  DZ: 'الجزائر',
  AS: 'ساموا الأمريكية',
  AD: 'أندورا',
  AO: 'أنغولا',
  AI: 'أنغويلا',
  AQ: 'أنتاركتيكا',
  AG: 'أنتيغوا وبربودا',
  AR: 'الأرجنتين',
  AM: 'أرمينيا',
  AW: 'أروبا',
  AU: 'أستراليا',
  AT: 'النمسا',
  AZ: 'أذربيجان',
  BS: 'الباهاما',
  BH: 'البحرين',
  BD: 'بنغلاديش',
  BB: 'بربادوس',
  BY: 'بيلاروسيا',
  BE: 'بلجيكا',
  BZ: 'بليز',
  BJ: 'بنين',
  BM: 'برمودا',
  BT: 'بوتان',
  BO: 'بوليفيا',
  BQ: 'بونير وسانت يوساتيوس وسابا',
  BA: 'البوسنة والهرسك',
  BW: 'بوتسوانا',
  BV: 'جزيرة بوفيه',
  BR: 'البرازيل',
  IO: 'إقليم المحيط الهندي البريطاني',
  BN: 'بروناي',
  BG: 'بلغاريا',
  BF: 'بوركينا فاسو',
  BI: 'بوروندي',
  CV: 'الرأس الأخضر',
  KH: 'كمبوديا',
  CM: 'الكاميرون',
  CA: 'كندا',
  KY: 'جزر كايمان',
  CF: 'جمهورية أفريقيا الوسطى',
  TD: 'تشاد',
  CL: 'تشيلي',
  CN: 'الصين',
  CX: 'جزيرة الكريسماس',
  CC: 'جزر كوكوس',
  CO: 'كولومبيا',
  KM: 'جزر القمر',
  CD: 'جمهورية الكونغو الديمقراطية',
  CG: 'جمهورية الكونغو',
  CK: 'جزر كوك',
  CR: 'كوستاريكا',
  HR: 'كرواتيا',
  CU: 'كوبا',
  CW: 'كوراساو',
  CY: 'قبرص',
  CZ: 'التشيك',
  CI: 'ساحل العاج',
  DK: 'الدنمارك',
  DJ: 'جيبوتي',
  DM: 'دومينيكا',
  DO: 'جمهورية الدومينيكان',
  EC: 'الإكوادور',
  EG: 'مصر',
  SV: 'السلفادور',
  GQ: 'غينيا الاستوائية',
  ER: 'إريتريا',
  EE: 'إستونيا',
  SZ: 'إسواتيني',
  ET: 'إثيوبيا',
  FK: 'جزر فوكلاند',
  FO: 'جزر فارو',
  FJ: 'فيجي',
  FI: 'فنلندا',
  FR: 'فرنسا',
  GF: 'غويانا الفرنسية',
  PF: 'بولينيزيا الفرنسية',
  TF: 'الأقاليم الجنوبية الفرنسية',
  GA: 'الغابون',
  GM: 'غامبيا',
  GE: 'جورجيا',
  DE: 'ألمانيا',
  GH: 'غانا',
  GI: 'جبل طارق',
  GR: 'اليونان',
  GL: 'جرينلاند',
  GD: 'غرينادا',
  GP: 'جوادلوب',
  GU: 'غوام',
  GT: 'غواتيمالا',
  GG: 'غيرنزي',
  GN: 'غينيا',
  GW: 'غينيا بيساو',
  GY: 'غيانا',
  HT: 'هايتي',
  HM: 'جزيرة هيرد وجزر ماكدونالد',
  VA: 'الفاتيكان',
  HN: 'هندوراس',
  HK: 'هونغ كونغ',
  HU: 'المجر',
  IS: 'آيسلندا',
  IN: 'الهند',
  ID: 'إندونيسيا',
  IR: 'إيران',
  IQ: 'العراق',
  IE: 'أيرلندا',
  IM: 'جزيرة مان',
  IL: 'إسرائيل',
  IT: 'إيطاليا',
  JM: 'جامايكا',
  JP: 'اليابان',
  JE: 'جيرزي',
  JO: 'الأردن',
  KZ: 'كازاخستان',
  KE: 'كينيا',
  KI: 'كيريباتي',
  KP: 'كوريا الشمالية',
  KR: 'كوريا الجنوبية',
  KW: 'الكويت',
  KG: 'قيرغيزستان',
  LA: 'لاوس',
  LV: 'لاتفيا',
  LB: 'لبنان',
  LS: 'ليسوتو',
  LR: 'ليبيريا',
  LY: 'ليبيا',
  LI: 'ليختنشتاين',
  LT: 'ليتوانيا',
  LU: 'لوكسمبورغ',
  MO: 'ماكاو',
  MG: 'مدغشقر',
  MW: 'مالاوي',
  MY: 'ماليزيا',
  MV: 'المالديف',
  ML: 'مالي',
  MT: 'مالطا',
  MH: 'جزر مارشال',
  MQ: 'مارتينيك',
  MR: 'موريتانيا',
  MU: 'موريشيوس',
  YT: 'مايوت',
  MX: 'المكسيك',
  FM: 'ميكرونيزيا',
  MD: 'مولدوفا',
  MC: 'موناكو',
  MN: 'منغوليا',
  ME: 'الجبل الأسود',
  MS: 'مونتسرات',
  MA: 'المغرب',
  MZ: 'موزمبيق',
  MM: 'ميانمار',
  NA: 'ناميبيا',
  NR: 'ناورو',
  NP: 'نيبال',
  NL: 'هولندا',
  NC: 'كاليدونيا الجديدة',
  NZ: 'نيوزيلندا',
  NI: 'نيكاراغوا',
  NE: 'النيجر',
  NG: 'نيجيريا',
  NU: 'نيوي',
  NF: 'جزيرة نورفولك',
  MP: 'جزر ماريانا الشمالية',
  NO: 'النرويج',
  OM: 'عُمان',
  PK: 'باكستان',
  PW: 'بالاو',
  PS: 'فلسطين',
  PA: 'بنما',
  PG: 'بابوا غينيا الجديدة',
  PY: 'باراغواي',
  PE: 'بيرو',
  PH: 'الفلبين',
  PN: 'جزر بيتكيرن',
  PL: 'بولندا',
  PT: 'البرتغال',
  PR: 'بورتوريكو',
  QA: 'قطر',
  MK: 'مقدونيا الشمالية',
  RO: 'رومانيا',
  RU: 'روسيا',
  RW: 'رواندا',
  RE: 'ريونيون',
  BL: 'سانت بارتيليمي',
  SH: 'سانت هيلانة',
  KN: 'سانت كيتس ونيفيس',
  LC: 'سانت لوسيا',
  MF: 'سانت مارتن (الجزء الفرنسي)',
  PM: 'سان بيير وميكلون',
  VC: 'سانت فينسنت والغرينادين',
  WS: 'ساموا',
  SM: 'سان مارينو',
  ST: 'ساو تومي وبرينسيب',
  SA: 'المملكة العربية السعودية',
  SN: 'السنغال',
  RS: 'صربيا',
  SC: 'سيشل',
  SL: 'سيراليون',
  SG: 'سنغافورة',
  SX: 'سينت مارتن (الجزء الهولندي)',
  SK: 'سلوفاكيا',
  SI: 'سلوفينيا',
  SB: 'جزر سليمان',
  SO: 'الصومال',
  ZA: 'جنوب أفريقيا',
  GS: 'جورجيا الجنوبية وجزر ساندويتش الجنوبية',
  SS: 'جنوب السودان',
  ES: 'إسبانيا',
  LK: 'سريلانكا',
  SD: 'السودان',
  SR: 'سورينام',
  SJ: 'سفالبارد ويان ماين',
  SE: 'السويد',
  CH: 'سويسرا',
  SY: 'سوريا',
  TW: 'تايوان',
  TJ: 'طاجيكستان',
  TZ: 'تنزانيا',
  TH: 'تايلاند',
  TL: 'تيمور الشرقية',
  TG: 'توغو',
  TK: 'توكيلاو',
  TO: 'تونغا',
  TT: 'ترينيداد وتوباغو',
  TN: 'تونس',
  TR: 'تركيا',
  TM: 'تركمانستان',
  TC: 'جزر توركس وكايكوس',
  TV: 'توفالو',
  UG: 'أوغندا',
  UA: 'أوكرانيا',
  AE: 'الإمارات العربية المتحدة',
  GB: 'المملكة المتحدة لبريطانيا العظمى وأيرلندا الشمالية',
  UM: 'جزر الولايات المتحدة النائية',
  US: 'الولايات المتحدة الأمريكية',
  UY: 'أوروغواي',
  UZ: 'أوزبكستان',
  VU: 'فانواتو',
  VE: 'فنزويلا (جمهورية فنزويلا البوليفارية)',
  VN: 'فيتنام',
  VG: 'جزر فيرجن البريطانية',
  VI: 'جزر فيرجن الأمريكية',
  WF: 'واليس وفوتونا',
  EH: 'الصحراء الغربية',
  YE: 'اليمن',
  ZM: 'زامبيا',
  ZW: 'زيمبابوي',
  AX: 'جزر أولاند',
  XK: 'كوسوفو',
  AC: 'أسينشين',
  TA: 'تريستان دا كونا',
};
