export enum CreateAdActionTypes {
  SET_CHANNEL = 'Set Channel',
  SET_POST = 'Set Post',
  SET_GOAL = 'Set Goal',
  SET_AD_SUGGESTIONS = 'Set Ad Sugguestions',
  SET_AI_SUGGESTIONS = 'Set AI Suggestions',
  DELETE_INTEREST = 'Delete Interest Suggestion',
  DELETE_DEMOGRAPHIC = 'Delete Demographic Suggestion',
  DELETE_BEHAVIOUR = 'Delete Behaviour Suggestion',
  SET_INTERESTS = 'Set Interest Suggestion',
  SET_DEMOGRAPHICS = 'Set Demographic Suggestion',
  SET_BEHAVIOURS = 'Set Behaviour Suggestion',
  ADD_INTEREST = 'Add Interest Suggestion',
  ADD_DEMOGRAPHIC = 'Add Demographic Suggestion',
  ADD_BEHAVIOUR = 'Add Behaviour Suggestion',
  UPDATE_BUDGET_DURATION = 'Update Ad Budget and Duration',
  UPDATE_AUDIANCE_GENDER = 'Update Ad Audiance Gender',
  UPDATE_AUDIANCE_AGE = 'Update Ad Audiance Age',
  ADD_COUNTRY = 'Add User Country',
  SET_CITIES = 'Set Ad Cities',
  ADD_CITY = 'Add Ad City',
  SET_AREAS = 'Set Ad Areas',
  ADD_AREA = 'Add Ad Area',
  DELETE_CITY = 'Delete Ad City',
  DELETE_AREA = 'Delete Ad Area',
  RESET = 'Reset',
}
