export const CampaignActionTypes = {
  GET_BRAND_LIST: 'get brand list',
  GET_BRAND_LOCATION_LIST: 'get brand location list',
  GET_BUDGETS: 'get budgets',
  SET_BRAND: 'set brand',
  // SET_LANG_CODE: 'set land code',
  // SET_HEADLINES: 'set headlines',
  // SET_DESCRIPTION: 'set description',
  // SET_KEYWORD: 'set keyword',
  SET_BUDGET: 'set budget',
  SET_CUSTOM_BUDGET: 'set custom budget',
  SET_LOCATIONS: 'set locations',
  SET_TARGET_FORM: 'set target form',
  SET_AD_CAMPAIGN_FORM: 'set ad campaign form',
  SET_PROXIMITY: 'set proximity',
  SET_BRANCH_INFO: 'set branch info',
  SET_KEYWORD_PLANNER: 'set keyword planner',
  SET_DEFAULT_LOCATION: 'set default location',
  RESET_CAMPAIGN_STATE: 'reset campaign state',
} as const;
