export interface AdDetailsAdInsights {
  comment: number | null;
  linkClick: number | null;
  messagingFirstReply: null | number;
  messaging_first_reply: null | number;
  landingPageView: number | null;
  viewContent: number | null;
  messagingConversationStarted7d: number | null;
  postEngagement: number | null;
  pageEngagement: number | null;
  clicks: number | null;
  frequency: number | null;
  videoView: number | null;
  like: number | null;
  reach: number | null;
  impressions: number | null;
  photoView: number | null;
  omniViewContent: number | null;
  postReaction: number | null;
  totalCpc: number;
  totalCostPerUniqueClick: number;
  totalCostPerInlineLinkClick: number;
  totalCostPerUniqueInlineLinkClick: number;
  totalCostPerInlinePostEngagement: number;
  totalCtr: number;
  totalInlinePostEngagement: number;
  totalInlineInlineLinkClicks: number;
  totalInlineInlineLinkCtr: number;
  lead: null;
  leadgenGrouped: null;
  leadGrouped: null;
  startDate: string | null;
  endDate: string | null;
  totalPageLikes: number;
  totalCostPerActionPageLike: number;
  totalCostPerActionVideoView: number;
  CostPerActionUniquePageLike: number;
  totalCostPerActionUniqueVideoView: number;
  costPerActionType: {
    linkClick: number;
    messagingConversationStarted7d: number;
    other: number;
    like: number;
    videoView: number;
    messagingFirstReply: number;
    postEngagement: number;
    pageEngagement: number;
  };
  costPerUniqueActionType: {
    linkClick: number | null;
    messagingConversationStarted7d: number | null;
    other: number | null;
    messagingFirstReply: number | null;
    postEngagement: number | null;
    pageEngagement: number | null;
    videoView: number | null;
    pageLike: number | null;
  };
}
